import { PRICES } from '@/lib/prices'

export const TIERS = [
  {
    tag: null as string | null,
    name: 'Basic Lease',
    colLabel: 'BASIC LEASE',
    price: `From $${PRICES.standard[1]}`,
    cta: 'Shop Beats',
    href: '/store',
    accent: false,
    features: [
      { label: 'File Format',        value: 'MP3 (320kbps)' },
      { label: 'Distribution Limit', value: '10,000 copies' },
      { label: 'Streaming Limit',    value: '100,000 streams' },
      { label: 'Music Videos',       value: '1 music video' },
      { label: 'Radio Broadcasting', value: 'Up to 2 stations' },
      { label: 'Monetization',       value: 'YouTube monetization' },
      { label: 'Credit Required',    value: 'Prod. KJYOUCRAZY' },
      { label: 'Ownership',          value: 'Non-exclusive' },
      { label: 'Live Performances',  value: 'Unlimited' },
    ],
  },
  {
    tag: null as string | null,
    name: 'Premium Lease',
    colLabel: 'PREMIUM LEASE',
    price: `From $${PRICES.premium[1]}`,
    cta: 'Shop Beats',
    href: '/store',
    accent: false,
    features: [
      { label: 'File Format',        value: 'WAV (24-bit)' },
      { label: 'Distribution Limit', value: '25,000 copies' },
      { label: 'Streaming Limit',    value: '500,000 streams' },
      { label: 'Music Videos',       value: '1 music video' },
      { label: 'Radio Broadcasting', value: 'Up to 5 stations' },
      { label: 'Monetization',       value: 'YouTube monetization' },
      { label: 'Credit Required',    value: 'Prod. KJYOUCRAZY' },
      { label: 'Ownership',          value: 'Non-exclusive' },
      { label: 'Live Performances',  value: 'Unlimited' },
    ],
  },
  {
    tag: 'Most Popular' as string | null,
    name: 'Unlimited Lease',
    colLabel: 'UNLIMITED LEASE',
    price: `From $${PRICES.unlimited[1]}`,
    cta: 'Shop Beats',
    href: '/store',
    accent: true,
    features: [
      { label: 'File Format',        value: 'WAV Trackout Stems' },
      { label: 'Distribution Limit', value: '75,000 copies' },
      { label: 'Streaming Limit',    value: '1,500,000 streams' },
      { label: 'Music Videos',       value: 'Unlimited' },
      { label: 'Radio Broadcasting', value: 'Unlimited' },
      { label: 'Monetization',       value: 'Full monetization' },
      { label: 'Credit Required',    value: 'Prod. KJYOUCRAZY' },
      { label: 'Ownership',          value: 'Non-exclusive' },
      { label: 'Live Performances',  value: 'Unlimited' },
    ],
  },
  {
    tag: null as string | null,
    name: 'Exclusive',
    colLabel: 'EXCLUSIVE',
    price: '$500+',
    cta: 'Contact Us',
    href: '/about',
    accent: false,
    features: [
      { label: 'File Format',        value: 'WAV + Stems + MP3' },
      { label: 'Distribution Limit', value: 'Unlimited' },
      { label: 'Streaming Limit',    value: 'Unlimited' },
      { label: 'Music Videos',       value: 'Unlimited' },
      { label: 'Radio Broadcasting', value: 'Unlimited' },
      { label: 'Monetization',       value: 'Full monetization' },
      { label: 'Credit Required',    value: 'Prod. KJYOUCRAZY' },
      { label: 'Ownership',          value: 'Full exclusive rights' },
      { label: 'Live Performances',  value: 'Unlimited' },
    ],
  },
]
