import { Beat } from './store'

export const PLACEHOLDER_BEATS: Beat[] = [
  {
    id: 'beat-1',
    title: 'Dark Intentions',
    bpm: 140,
    key: 'Am',
    genre: 'Trap',
    subgenre: 'Dark Trap',
    tags: ['dark', 'hard', '808s'],
    file_url: null,
    preview_url: null,
    cover_url: null,
    stems_path: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'beat-2',
    title: 'Midnight Drill',
    bpm: 145,
    key: 'Dm',
    genre: 'Drill',
    subgenre: 'UK Drill',
    tags: ['drill', 'UK', 'strings'],
    file_url: null,
    preview_url: null,
    cover_url: null,
    stems_path: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'beat-3',
    title: 'Velvet Nights',
    bpm: 90,
    key: 'Gm',
    genre: 'R&B',
    subgenre: 'Neo Soul',
    tags: ['smooth', 'vibes', 'melodic'],
    file_url: null,
    preview_url: null,
    cover_url: null,
    stems_path: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'beat-4',
    title: 'Lagos Wave',
    bpm: 105,
    key: 'Cm',
    genre: 'Afrobeats',
    subgenre: 'Afropop',
    tags: ['afro', 'drums', 'energy'],
    file_url: null,
    preview_url: null,
    cover_url: null,
    stems_path: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'beat-5',
    title: 'Slide Season',
    bpm: 138,
    key: 'Fm',
    genre: 'Trap',
    subgenre: 'Melodic Trap',
    tags: ['melodic', 'piano', 'trap'],
    file_url: null,
    preview_url: null,
    cover_url: null,
    stems_path: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'beat-6',
    title: 'Block Talk',
    bpm: 143,
    key: 'Bm',
    genre: 'Drill',
    subgenre: 'NY Drill',
    tags: ['NY', 'grimey', '808'],
    file_url: null,
    preview_url: null,
    cover_url: null,
    stems_path: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'beat-7',
    title: 'Golden Hour',
    bpm: 85,
    key: 'Em',
    genre: 'R&B',
    subgenre: 'Trap R&B',
    tags: ['chill', 'melodic', 'late night'],
    file_url: null,
    preview_url: null,
    cover_url: null,
    stems_path: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'beat-8',
    title: 'Naija Bounce',
    bpm: 112,
    key: 'Am',
    genre: 'Afrobeats',
    subgenre: 'Afroswing',
    tags: ['swing', 'danceable', 'bass'],
    file_url: null,
    preview_url: null,
    cover_url: null,
    stems_path: null,
    is_active: true,
    created_at: new Date().toISOString(),
  },
]
